services:
  postgresql:
    container_name: postgresql5
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin " ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin5
    image: dpage/pgadmin4:6.20
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - 5050:80

  worker_service:
      build: ./worker_service
      ports:
        - '8080:8080'
      depends_on:
        postgresql:
          condition: service_healthy

#  points_service:
#      build: ./points_service
#      ports:
#        - '8081:8081'
#      depends_on:
#        postgresql:
#          condition: service_healthy
#
#  manager_service:
#      build: ./manager_service
#      ports:
#        - '8082:8082'
#      depends_on:
#        postgresql:
#          condition: service_healthy
