services:
  postgresql:
    container_name: postgresql5
    image: postgres:15.2
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin " ]
      interval: 10s
      timeout: 5s
      retries: 5

  worker_service:
      build: ./worker_service
      ports:
        - '8080:8080'
      depends_on:
        postgresql:
          condition: service_healthy

  points_service:
      build: ./points_service
      ports:
        - '8081:8081'
      depends_on:
        postgresql:
          condition: service_healthy

  manager_service:
      build: ./manager_service
      ports:
        - '8082:8082'
      depends_on:
        postgresql:
          condition: service_healthy
  react:
    build: ./sovkombank_visitor
    ports:
      - "5173:5173"
